### ISSUE TITLE
Prefix doesn't work

### ISSUE THREAD

**Issue by CupidonSauce173** [poggit-orphanage/PureChat#16]
The prefix's doesn't work

1.Download PureChat
2.Drop it on the plugin directory
3.Start the server
4.Edit config.yml 

Example rank format : 
```
  Owner:
    chat: '&f{prefix}§4[§eO§6w§3n§9e§cr]&6&r {display_name} &e> {msg}'
    nametag: '&f{prefix}§4[§eO§6w§3n§9e§cr]&6&r {display_name}'
    worlds: []
```
5.reload or restart server 
6. /setprefix <test>
